"""Setup wizard — interactive first-run onboarding for non-technical users.

This is the brains of the ``init`` command. Its job is to remove the hardest
part of getting started with Jiramator: hand-editing YAML full of raw Jira
custom-field IDs. It:

    1. Collects the Jira URL and credentials, and tests the connection live.
    2. Auto-discovers custom field IDs *by name* via the Jira API, so the user
       picks "Story Points" instead of ``customfield_10026``.
    3. Validates the project key against Jira.
    4. Writes a ready-to-use org config and a commented team-config skeleton
       full of common, customizable examples.
    5. Sets up credentials (printed export commands or a gitignored ``.env``).

Interactive I/O lives here at the edge; the payload-building helpers
(``build_org_config_yaml``, ``build_team_skeleton_yaml``, ``discover_field_id``,
etc.) are pure and unit-tested. All real Jira communication goes through the
existing :class:`~jiramator.jira_client.JiraClient`.
"""

from __future__ import annotations

import os
import re
from pathlib import Path

from rich.console import Console
from rich.prompt import Confirm, IntPrompt, Prompt
from rich.table import Table

from jiramator.config import OrgConfig, SprintConfig
from jiramator.jira_client import JiraApiError, JiraClient

# ---------------------------------------------------------------------------
# Core field discovery
# ---------------------------------------------------------------------------

# Logical field name -> ordered list of likely Jira field display names.
# The first case-insensitive match wins. These are the fields `plan` relies on;
# users can map additional fields later for import/update (see the wiki).
_CORE_FIELD_CANDIDATES: dict[str, list[str]] = {
    "epic_link": ["Epic Link", "Parent Link", "Parent"],
    "story_points": ["Story Points", "Story point estimate", "Story Point Estimate"],
    "sprint_field": ["Sprint"],
}


def discover_field_id(
    fields: list[dict[str, object]], candidates: list[str]
) -> str | None:
    """Return the Jira field id whose name matches one of *candidates*.

    Matching is case-insensitive and honors candidate priority order (an
    earlier candidate always wins over a later one).

    Args:
        fields: Field metadata as returned by ``JiraClient.get_fields()``
            (each item has ``"id"`` and ``"name"`` keys).
        candidates: Ordered display names to look for.

    Returns:
        The matching field id, or ``None`` if nothing matched.
    """
    by_name: dict[str, str] = {}
    for f in fields:
        name = str(f.get("name", "")).strip().lower()
        fid = str(f.get("id", "")).strip()
        # Keep the first id seen for a given name (Jira may list duplicates).
        if name and fid and name not in by_name:
            by_name[name] = fid
    for candidate in candidates:
        fid = by_name.get(candidate.strip().lower())
        if fid is not None:
            return fid
    return None


# ---------------------------------------------------------------------------
# Pure helpers — slugs and YAML rendering
# ---------------------------------------------------------------------------


def slugify(name: str) -> str:
    """Turn a free-text name into a safe lowercase filename slug.

    ``"My Team!"`` -> ``"my-team"``. Falls back to ``"config"`` if empty.
    """
    slug = re.sub(r"[^a-z0-9]+", "-", name.strip().lower()).strip("-")
    return slug or "config"


def build_org_config_yaml(
    *,
    jira_url: str,
    jira_email_env: str,
    jira_token_env: str,
    custom_fields: dict[str, str],
    sprints: SprintConfig,
) -> str:
    """Render a ready-to-use org config YAML string.

    Only the fields ``plan`` needs are emitted; ``bulk_create`` (used by
    ``import``/``update``) is intentionally omitted and falls back to its
    defaults — a comment points users to the wiki for that.
    """
    lines: list[str] = [
        "# Org-level Jiramator configuration — generated by `jiramator init`.",
        "# Safe to edit by hand. Never put credentials in this file; they are",
        "# read from environment variables at runtime.",
        "",
        f"jira_url: {jira_url}",
        "",
        "# Credentials are read from these environment variables at runtime.",
        f"jira_email_env: {jira_email_env}",
        f"jira_token_env: {jira_token_env}",
        "",
        "# Logical name -> Jira custom field id, auto-discovered from your Jira.",
        "custom_fields:",
    ]
    if custom_fields:
        width = max(len(k) for k in custom_fields) + 1
        for name, fid in custom_fields.items():
            lines.append(f"  {(name + ':').ljust(width)} {fid}")
    else:
        lines.append("  {}")
    lines += [
        "",
        "# Bulk import/update (the `import` and `update` commands) needs an",
        "# additional `bulk_create:` block (field aliases + types). See:",
        "# https://github.com/dkim_mktx/jiramator/wiki/Import-and-Update-Details",
        "",
        "# PI sprint cadence.",
        "sprints:",
        f"  count: {sprints.count}",
        f"  standard_length_weeks: {sprints.standard_length_weeks}",
        f"  long_length_weeks: {sprints.long_length_weeks}",
        f"  long_sprints: [{', '.join(str(n) for n in sprints.long_sprints)}]",
        "",
    ]
    return "\n".join(lines)


def build_team_skeleton_yaml(
    *,
    project_key: str,
    team_name: str,
    epic_link_field: str,
) -> str:
    """Render a commented team-config skeleton with customizable examples.

    The examples are deliberately concrete (a regression-test per-release
    ticket and a prod-support per-sprint ticket) so a user can adapt them
    rather than build templates from scratch. ``{variables}`` are interpolated
    by the ticket builder at run time.
    """
    epic = epic_link_field or "customfield_XXXXX"
    return f"""\
# Team-level Jiramator configuration — generated by `jiramator init`.
#
# This is a STARTING POINT: the epics and ticket templates below are common
# examples. Edit them to match the tickets YOUR team creates every PI, then
# preview with:  jiramator plan --dry-run
#
# Template variables you can use anywhere in summaries/fields:
#   {{pi_num}}     -> e.g. 29          {{pi_label}}   -> e.g. PI29
#   {{version}}    -> a fix version    {{sprint_num}} -> sprint number
#   {{team_name}}  -> {team_name}

project_key: {project_key}
team_name: {team_name}

# Board id enables sprint assignment. Find it in your Jira board URL
# (…/RapidBoard.jspa?rapidView=<board_id>). Remove this line if unused.
# board_id: 123

# Whether this PI's sprints already exist in Jira. Set false to skip the
# board lookup, or omit to be asked each run.
sprints_exist: false

# ---------------------------------------------------------------------------
# Reuse epics that already exist in Jira instead of creating new ones.
# Map a short reference key to its real Jira issue key, then point tickets at
# it with "$epic:<key>" (see the examples below).
# ---------------------------------------------------------------------------
existing_epics:
  misc: {project_key}-1        # <-- replace with a real epic key, or delete

# ---------------------------------------------------------------------------
# Epics created fresh at the start of each PI. Leave empty if you only reuse
# existing epics above.
# ---------------------------------------------------------------------------
recurring_epics: []
# Example:
# recurring_epics:
#   - key: bau
#     summary: "{{team_name}} {{pi_label}} - Business as Usual"
#     fields:
#       issuetype: Epic

# ---------------------------------------------------------------------------
# Tickets generated once PER RELEASE version.
# With 2 fix versions, one template here produces 2 tickets.
# ---------------------------------------------------------------------------
per_release_tickets:
  - summary: "Testing - {{version}} Regression test"
    fields:
      issuetype: Task
      priority: Medium
      labels: ["{{pi_label}}", "Testing"]
      fixVersions: ["{{version}}"]
      {epic}: "$epic:misc"     # link to the 'misc' epic above

# ---------------------------------------------------------------------------
# Tickets generated once PER SPRINT.
# Standard sprints: 1 ticket each. Long sprints: extra tickets with a suffix.
# ---------------------------------------------------------------------------
per_sprint_tickets:
  - summary: "Prod Support (Sprint {{sprint_num}})"
    fields:
      issuetype: Task
      priority: Medium
      labels: ["{{pi_label}}", "Prod_Support"]
      {epic}: "$epic:misc"
    extra_on_long_sprint: 1
    long_sprint_suffix: ["a", "b"]   # e.g. Sprint 6 -> "6a" + "6b"
"""


def render_env_exports(email_env: str, token_env: str, email: str, token: str) -> str:
    """Render copy-paste shell export commands (bash/zsh and PowerShell)."""
    return (
        "# macOS / Linux (bash/zsh):\n"
        f"export {email_env}='{email}'\n"
        f"export {token_env}='{token}'\n"
        "\n"
        "# Windows PowerShell:\n"
        f"$env:{email_env}='{email}'\n"
        f"$env:{token_env}='{token}'"
    )


def render_env_file(email_env: str, token_env: str, email: str, token: str) -> str:
    """Render the contents of a ``.env`` file holding the credentials."""
    return (
        "# Jiramator credentials — generated by `jiramator init`.\n"
        "# This file contains a secret; it is gitignored. Do not commit or share it.\n"
        f"{email_env}={email}\n"
        f"{token_env}={token}\n"
    )


# ---------------------------------------------------------------------------
# .env / .gitignore helpers
# ---------------------------------------------------------------------------


def _ensure_gitignored(entry: str, gitignore: Path) -> None:
    """Append *entry* to *gitignore* if not already present."""
    existing = ""
    if gitignore.exists():
        existing = gitignore.read_text(encoding="utf-8")
        if any(line.strip() == entry for line in existing.splitlines()):
            return
    prefix = "" if existing.endswith("\n") or not existing else "\n"
    with gitignore.open("a", encoding="utf-8") as fh:
        fh.write(f"{prefix}{entry}\n")


# ---------------------------------------------------------------------------
# Interactive orchestration
# ---------------------------------------------------------------------------


def _prompt_jira_url(console: Console) -> str:
    """Prompt for the Jira base URL and validate it looks like a URL."""
    while True:
        url = Prompt.ask(
            "[bold]Your Jira base URL[/] (e.g. https://acme.atlassian.net)",
            console=console,
        ).strip().rstrip("/")
        if url.startswith(("http://", "https://")) and "." in url:
            return url
        console.print("[red]Please enter a full URL starting with https://[/]")


def _connect(
    console: Console, jira_url: str, email_env: str, token_env: str
) -> tuple[JiraClient, str, str]:
    """Prompt for credentials and return a live, verified client.

    Loops until the credentials authenticate. Sets the credentials in the
    process environment so the constructed client (and the rest of the wizard)
    can use them.

    Returns:
        (client, email, token)
    """
    while True:
        email = Prompt.ask("[bold]Your Jira email[/]", console=console).strip()
        token = Prompt.ask(
            "[bold]Your Jira API token[/] "
            "(create one at id.atlassian.com/manage-profile/security/api-tokens)",
            password=True,
            console=console,
        ).strip()

        os.environ[email_env] = email
        os.environ[token_env] = token

        placeholder_sprints = SprintConfig(
            count=6, standard_length_weeks=2, long_length_weeks=3, long_sprints=[6]
        )
        try:
            org = OrgConfig(
                jira_url=jira_url,  # type: ignore[arg-type]
                jira_email_env=email_env,
                jira_token_env=token_env,
                custom_fields={},
                sprints=placeholder_sprints,
            )
            client = JiraClient(org)
            console.print("  [dim]Testing connection…[/]")
            client.get_fields()  # cheap authenticated call
        except JiraApiError as exc:
            console.print(f"[red]Connection failed:[/] {exc}")
            if not Confirm.ask("Try different credentials?", default=True, console=console):
                raise
            continue
        except ValueError as exc:
            console.print(f"[red]{exc}[/]")
            continue

        console.print("[green]✓[/] Connected to Jira.")
        return client, email, token


def _discover_core_fields(
    console: Console, client: JiraClient
) -> dict[str, str]:
    """Auto-discover the core custom field ids, confirming each with the user."""
    fields = client.get_fields()
    resolved: dict[str, str] = {}

    console.print("\n[bold]── Discovering your Jira custom fields ──[/]\n")
    for logical, candidates in _CORE_FIELD_CANDIDATES.items():
        found = discover_field_id(fields, candidates)
        if found is not None:
            console.print(
                f"  [green]✓[/] {logical}: matched [cyan]{found}[/] "
                f"([dim]{candidates[0]}[/])"
            )
            resolved[logical] = found
        else:
            console.print(
                f"  [yellow]?[/] Could not auto-detect [bold]{logical}[/] "
                f"(looked for: {', '.join(candidates)})."
            )
            manual = Prompt.ask(
                f"    Enter the field id for {logical} "
                f"(e.g. customfield_10014), or leave blank to skip",
                default="",
                console=console,
            ).strip()
            if manual:
                resolved[logical] = manual
    return resolved


def _prompt_sprint_cadence(console: Console) -> SprintConfig:
    """Prompt for the PI sprint cadence."""
    console.print("\n[bold]── Sprint cadence ──[/]\n")
    count = IntPrompt.ask("How many sprints in a PI?", default=6, console=console)
    standard = IntPrompt.ask(
        "Standard sprint length (weeks)?", default=2, console=console
    )
    long_len = IntPrompt.ask(
        "Long sprint length (weeks)?", default=3, console=console
    )
    long_raw = Prompt.ask(
        "Which sprint numbers are long? (comma-separated, blank for none)",
        default=str(count),
        console=console,
    ).strip()
    long_sprints = [
        int(n) for n in re.split(r"[,\s]+", long_raw) if n.strip().isdigit()
    ]
    return SprintConfig(
        count=count,
        standard_length_weeks=standard,
        long_length_weeks=long_len,
        long_sprints=long_sprints,
    )


def _setup_credentials(
    console: Console, email_env: str, token_env: str, email: str, token: str, cwd: Path
) -> None:
    """Let the user pick how credentials are provided going forward."""
    console.print("\n[bold]── Credentials ──[/]\n")
    console.print(
        "Jiramator reads your token from an environment variable — it is never "
        "stored in config. How would you like to provide it going forward?"
    )
    choice = Prompt.ask(
        "  [1] Show me export commands to paste  "
        "[2] Save a gitignored .env file for me",
        choices=["1", "2"],
        default="1",
        console=console,
    )
    if choice == "2":
        env_path = cwd / ".env"
        env_path.write_text(
            render_env_file(email_env, token_env, email, token), encoding="utf-8"
        )
        _ensure_gitignored(".env", cwd / ".gitignore")
        console.print(
            f"[green]✓[/] Wrote [bold]{env_path}[/] (gitignored). Load it each "
            "session with:  [cyan]set -a && source .env && set +a[/]"
        )
    else:
        console.print(
            "\nPaste these into your terminal (they last for the current "
            "session):\n"
        )
        console.print(render_env_exports(email_env, token_env, email, token))


def run_init(
    console: Console | None = None,
    *,
    org_dir: Path | None = None,
    team_dir: Path | None = None,
    cwd: Path | None = None,
    force: bool = False,
) -> None:
    """Run the interactive setup wizard.

    Args:
        console: Rich console for output (created if omitted).
        org_dir: Directory to write the org config into (default ``configs/org``).
        team_dir: Directory for the team config (default ``configs/teams``).
        cwd: Base directory for ``.env``/``.gitignore`` (default: current dir).
        force: Overwrite existing config files without asking.
    """
    if console is None:
        console = Console(stderr=True)
    org_dir = org_dir or Path("configs/org")
    team_dir = team_dir or Path("configs/teams")
    cwd = cwd or Path.cwd()

    console.print("\n[bold]══ Jiramator setup ══[/]\n")
    console.print(
        "This will connect to Jira, discover your field ids, and write your "
        "org and team config files. Let's go.\n"
    )

    email_env, token_env = "JIRA_EMAIL", "JIRA_TOKEN"

    jira_url = _prompt_jira_url(console)
    client, email, token = _connect(console, jira_url, email_env, token_env)

    custom_fields = _discover_core_fields(console, client)

    # -- Project key (validated) -------------------------------------------
    console.print("\n[bold]── Your team ──[/]\n")
    while True:
        project_key = Prompt.ask(
            "[bold]Jira project key[/] (e.g. CA)", console=console
        ).strip().upper()
        try:
            project = client.get_project(project_key)
            console.print(
                f"[green]✓[/] Found project [bold]{project_key}[/] "
                f"({project.get('name', project_key)})."
            )
            break
        except JiraApiError as exc:
            console.print(f"[red]{exc}[/]")
            if not Confirm.ask("Try a different key?", default=True, console=console):
                break

    team_name = Prompt.ask(
        "[bold]Team name[/] (used in ticket summaries)", console=console
    ).strip()

    sprints = _prompt_sprint_cadence(console)

    # -- Write config files -------------------------------------------------
    org_dir.mkdir(parents=True, exist_ok=True)
    team_dir.mkdir(parents=True, exist_ok=True)
    org_path = org_dir / f"{slugify(team_name)}.yaml"
    team_path = team_dir / f"{slugify(team_name)}.yaml"

    for path in (org_path, team_path):
        if path.exists() and not force:
            if not Confirm.ask(
                f"[yellow]{path} exists. Overwrite?[/]", default=False, console=console
            ):
                console.print("[red]Aborted.[/] Existing config left untouched.")
                return

    org_path.write_text(
        build_org_config_yaml(
            jira_url=jira_url,
            jira_email_env=email_env,
            jira_token_env=token_env,
            custom_fields=custom_fields,
            sprints=sprints,
        ),
        encoding="utf-8",
    )
    team_path.write_text(
        build_team_skeleton_yaml(
            project_key=project_key,
            team_name=team_name,
            epic_link_field=custom_fields.get("epic_link", ""),
        ),
        encoding="utf-8",
    )
    console.print(f"\n[green]✓[/] Wrote org config:  [bold]{org_path}[/]")
    console.print(f"[green]✓[/] Wrote team config: [bold]{team_path}[/]")

    _setup_credentials(console, email_env, token_env, email, token, cwd)

    # -- Next steps ---------------------------------------------------------
    console.print("\n[bold green]══ Setup complete ══[/]\n")
    table = Table(show_header=False, box=None, pad_edge=False)
    table.add_column(style="dim")
    table.add_row("1.", f"Edit your team's tickets in [cyan]{team_path}[/]")
    table.add_row("2.", "Preview a PI (creates nothing): [cyan]jiramator plan --dry-run[/]")
    table.add_row("3.", "When it looks right, run [cyan]jiramator plan[/] to create them.")
    console.print(table)
    console.print(
        "\n[dim]Full docs: https://github.com/dkim_mktx/jiramator/wiki[/]\n"
    )
